project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!CLAUDE.md"

execute:
    freeze: auto

publish:
  gh-pages: true

website:
  favicon: img/izzilab_logo.png
  title: "Izzi Lab"
  navbar:
    background: primary
    right:
      - href: news.qmd
        text: News
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
      - href: opportunities.qmd
        text: Opportunities
      - href: contact.qmd
        text: Contact
  page-footer:
    background: "#3D5A73"
    foreground: light
    left: |
      <img src="/img/izzilab_logo.png" alt="Izzi Lab" height="40" style="margin-right: 10px; vertical-align: middle;">
      <span style="vertical-align: middle;">Izzi Lab</span>
    center: |
      [Research](/research.html) | [Publications](/publications.html) | [Contact](/contact.html)
    right: |
      <a href="https://github.com/izzilab" style="color: white; margin-right: 10px;"><i class="fab fa-github"></i></a>
      <a href="https://twitter.com/ValerioIzzi" style="color: white; margin-right: 10px;"><i class="fab fa-x-twitter"></i></a>
      <a href="https://scholar.google.com/citations?user=qZ8_jowAAAAJ" style="color: white;"><i class="fab fa-google-scholar"></i></a>
    border: false
  google-analytics: ""
  site-url: https://theayomideo.github.io/izzilab
  repo-url: https://github.com/theayomideo/izzilab

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
