project:
  type: website
  output-dir: docs

execute:
    freeze: auto

website:
  favicon: img/izzilab_logo.png
  title: "Izzi Lab"
  navbar:
    background: primary
    right:
      - href: news.qmd
        text: News
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
      - href: opportunities.qmd
        text: Opportunities
      - href: contact.qmd
        text: Contact
  page-footer: "Copyright 2025 &copy; Izzi Lab - University of Oulu"
  google-analytics: ""
  site-url: https://theayomideo.github.io/izzilab
  repo-url: https://github.com/theayomideo/izzilab

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
